Repository desenho-2019/WebAPP, pull requests merged in 2019-10, with the labels that each got.

#5 [US36] Tela de Login
  cafofo/package-lock.json
  cafofo/package.json
  cafofo/src/App.js
  cafofo/src/components/header/styles.css
  cafofo/src/pages/forgotPassword/index.js
  cafofo/src/pages/forgotPassword/styles.css
  cafofo/src/pages/login/index.css
  cafofo/src/pages/login/index.js
  cafofo/src/pages/login/styles.js
  cafofo/src/pages/userRegister/index.js
  cafofo/src/pages/userRegister/styles.js
  cafofo/yarn.lock
  package-lock.json
Labels: frontend, login

#7 [US02] - Recuperar Senha
  cafofo/src/pages/forgotPassword/index.js
  cafofo/src/pages/forgotPassword/styles.css
  cafofo/src/pages/forgotPassword/styles.js
Labels: cadastro

#16 #3 Fixing button and required fields
  cafofo/src/pages/userRegister/index.js
  cafofo/src/pages/userRegister/styles.js
Labels: cadastro

#17 US39 Visualizar Página Principal
  cafofo/package-lock.json
  cafofo/public/cafofo_favicon.ico
  cafofo/public/cafofo_favicon.png
  cafofo/public/favicon.ico
  cafofo/public/index.html
  cafofo/public/logo192.png
  cafofo/public/logo512.png
  cafofo/src/App.js
  cafofo/src/components/header/index.js
  cafofo/src/components/header/styles.css
  cafofo/src/pages/adslist/index.js
  cafofo/src/pages/adslist/styles.css
  cafofo/src/pages/main/cafofoback.jpg
  cafofo/src/pages/main/index.js
  cafofo/src/pages/main/styles.css
  cafofo/src/pages/userRegister/index.js
  cafofo/src/pages/userRegister/styles.js
Labels: frontend
